# Generated by Django 3.1.5 on 2021-01-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
